version: "3.7"  # optional since v1.27.0
services:
  back:
    build: backend/
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    network_mode: "host"
    ports:
      - 4200:4200
    container_name: trivia_frontend
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/chat-ui/node_modules

